<?php

namespace Database\Seeders;

use App\Models\JenisPilihanKualitatif;
use App\Models\Role;
use App\Models\User;
use App\Models\Zona;
use App\Models\Satuan;
use App\Models\Parameter;
use App\Models\TitikPengamatan;
use Illuminate\Database\Seeder;
use App\Models\KategoriParameter;
use App\Models\ParameterTitikPengamatan;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Role::insert([
            ['nama' => 'Sistem Admin'],
            ['nama' => 'Pemimpin'],
            ['nama' => 'Kabag Pabrikasi'],
            ['nama' => 'Kabag Teknik'],
            ['nama' => 'Kasie Pabrikasi'],
            ['nama' => 'Kasie Teknik'],
            ['nama' => 'Kasubsie Pabrikasi'],
            ['nama' => 'Kasubsie Teknik'],
            ['nama' => 'Koordinator QC'],
            ['nama' => 'Koordinator Pabrikasi'],
            ['nama' => 'Admin QC'],
            ['nama' => 'Mandor QC'],
            ['nama' => 'Operator Masakan'],
            ['nama' => 'Operator Imbibisi'],
            ['nama' => 'Tanaman'],
            ['nama' => 'TUK'],
            ['nama' => 'Tamu'],
        ]);

        User::insert([
            [
                'role_id' => 1,
                'name' => ucwords('Andik Kurniawan'),
                'email' => "andik@mdp.com",
                'password' => bcrypt('password987'),
            ],
            [
                'role_id' => 2,
                'name' => ucwords('arifin'),
                'email' => "arifin@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 3,
                'name' => ucwords('tri sunu hardi'),
                'email' => "sunu@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 4,
                'name' => ucwords('agung nugroho'),
                'email' => "agung@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 5,
                'name' => ucwords('sri winarno'),
                'email' => "win@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 5,
                'name' => ucwords('tataq seviarto'),
                'email' => "tataq@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 6,
                'name' => ucwords('cucut hendra p.'),
                'email' => "cucut@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 6,
                'name' => ucwords('gunadi widya p.'),
                'email' => "gunadi@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 7,
                'name' => ucwords('firmansyah agil saputra'),
                'email' => "agil@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 7,
                'name' => ucwords('mohammad faiz rosidin'),
                'email' => "faiz@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 7,
                'name' => ucwords('m. aulia ramadhan'),
                'email' => "rama@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 7,
                'name' => ucwords('m. yanuar ananta'),
                'email' => "yanuar@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 7,
                'name' => ucwords('vicky dwi putra'),
                'email' => "vicky@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 8,
                'name' => ucwords('m. nur harfianto'),
                'email' => "harfi@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 8,
                'name' => ucwords('sarjono a. putro'),
                'email' => "sarjono@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 8,
                'name' => ucwords('surya ramadhana'),
                'email' => "surya@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 8,
                'name' => ucwords('ananta jatra s.'),
                'email' => "ananta@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 9,
                'name' => ucwords('yudi suyadi'),
                'email' => "yudi@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('achmad zauzi rifqi'),
                'email' => "zauzi@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('fery ardianto'),
                'email' => "fery@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('rangga wisnu w.'),
                'email' => "rangga@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('tutus agustyn rafzhanyani'),
                'email' => "tutus@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('lina ulfa kusumastuti'),
                'email' => "lina@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('dita putri pertiwi'),
                'email' => "dita@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 11,
                'name' => ucwords('hariyanto'),
                'email' => "hariyanto@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 12,
                'name' => ucwords('risky anggara'),
                'email' => "risky@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 12,
                'name' => ucwords('nico aldy dwi putra'),
                'email' => "nico@mdp.com",
                'password' => bcrypt('password'),
            ],
            [
                'role_id' => 12,
                'name' => ucwords('dwi wahyu nugroho'),
                'email' => "dwi_wahyu@mdp.com",
                'password' => bcrypt('password'),
            ],
        ]);

        // Insert kategori parameter
        KategoriParameter::insert([
            ['nama' => 'Analisa Lab'],
            ['nama' => 'Proses'],
            ['nama' => 'Penggunaan Bahan'],
            ['nama' => 'Taksasi Proses'],
            ['nama' => 'Utilitas'],
            // ['nama' => 'Lingkungan'],
        ]);

        // Insert satuan
        Satuan::insert([
            ['nama' => 'Persen', 'simbol' => '%'],
            ['nama' => 'ICUMSA', 'simbol' => 'IU'],
            ['nama' => 'Derajat Pol', 'simbol' => '°ZK'],
            ['nama' => 'pH', 'simbol' => 'pH'],
            ['nama' => 'Nephelometric Turbidity Unit', 'simbol' => 'NTU'],
            ['nama' => 'PPM', 'simbol' => 'ppm'],
            ['nama' => 'Milimeter', 'simbol' => 'mm'],
            ['nama' => 'Celcius', 'simbol' => '°C'],
            ['nama' => 'Kilogram', 'simbol' => 'kg'],
            ['nama' => 'Gram', 'simbol' => 'g'],
            ['nama' => 'Ton', 'simbol' => 't'],
            ['nama' => 'Kuintal', 'simbol' => 'ku'],
            ['nama' => 'Meter Kubik', 'simbol' => 'm³'],
            ['nama' => 'Hectoliter', 'simbol' => 'hL'],
            ['nama' => 'Pan', 'simbol' => 'p'],
            // ['nama' => 'Kelvin', 'simbol' => 'K'],
            // ['nama' => 'Ampere', 'simbol' => 'A'],
            // ['nama' => 'Volt', 'simbol' => 'V'],
            // ['nama' => 'Watt', 'simbol' => 'W'],
            // ['nama' => 'Kilowatt', 'simbol' => 'kW'],
            // ['nama' => 'Megawatt', 'simbol' => 'MW'],
            // ['nama' => 'Kilowatt-hour', 'simbol' => 'kWh'],
            // ['nama' => 'Putaran per Menit', 'simbol' => 'Persen'],
            // ['nama' => 'Pascal', 'simbol' => 'Pa'],
            // ['nama' => 'Kilopascal', 'simbol' => 'kPa'],
            // ['nama' => 'Bar', 'simbol' => 'bar'],
            // ['nama' => 'Liter', 'simbol' => 'L'],
            // ['nama' => 'Mililiter', 'simbol' => 'mL'],
            // ['nama' => 'Meter Kubik per Jam', 'simbol' => 'm³/h'],
            // ['nama' => 'Liter per Menit', 'simbol' => 'L/min'],
            // ['nama' => 'Persentase', 'simbol' => '%'],
            // ['nama' => 'Newton', 'simbol' => 'N'],
            // ['nama' => 'Kilonewton', 'simbol' => 'kN'],
            // ['nama' => 'Meter', 'simbol' => 'm'],
            // ['nama' => 'Centimeter', 'simbol' => 'cm'],
            // ['nama' => 'Jam', 'simbol' => 'h'],
            // ['nama' => 'Menit', 'simbol' => 'min'],
            // ['nama' => 'Detik', 'simbol' => 's'],
            // ['nama' => 'Lux', 'simbol' => 'lx'],
            // ['nama' => 'Decibel', 'simbol' => 'dB'],
            // ['nama' => 'Hz', 'simbol' => 'Hz'],
            // ['nama' => 'Ohm', 'simbol' => 'Ω'],
            // ['nama' => 'Siklus', 'simbol' => 'cycle'],
            // ['nama' => 'Jumlah', 'simbol' => 'unit'],
            // ['nama' => 'Kalori', 'simbol' => 'cal'],
            // ['nama' => 'Joule', 'simbol' => 'J'],
            // ['nama' => 'Kandungan Air', 'simbol' => '%RH'],
            // ['nama' => 'pH', 'simbol' => 'pH'],
            // ['nama' => 'Brix', 'simbol' => '°Bx'],
            // ['nama' => 'Tegangan', 'simbol' => 'MPa'],
            // ['nama' => 'Kecepatan Alir', 'simbol' => 'm/s'],
            // ['nama' => 'Frekuensi', 'simbol' => '1/s'],
            // ['nama' => 'Energi Termal', 'simbol' => 'BTU'],
            // ['nama' => 'Lumen', 'simbol' => 'lm'],
            // ['nama' => 'Density', 'simbol' => 'kg/m³'],
            // ['nama' => 'Konsentrasi', 'simbol' => 'mol/L'],
        ]);

        JenisPilihanKualitatif::insert([
            // Untuk parameter_id 1 → status mesin
            ['keterangan' => 'Aktif'],
            ['keterangan' => 'Nonaktif'],

            // Untuk parameter_id 2 → konfirmasi
            ['keterangan' => 'Ya'],
            ['keterangan' => 'Tidak'],

            // Untuk parameter_id 3 → kondisi umum
            ['keterangan' => 'Baik'],
            ['keterangan' => 'Cukup'],
            ['keterangan' => 'Buruk'],

            // Untuk parameter_id 4 → level
            ['keterangan' => 'Rendah'],
            ['keterangan' => 'Sedang'],
            ['keterangan' => 'Tinggi'],

            // Untuk parameter_id 5 → warna indikator
            // ['keterangan' => 'Hijau'],
            // ['keterangan' => 'Kuning'],
            // ['keterangan' => 'Merah'],

            // Untuk parameter_id 6 → mode kerja
            // ['keterangan' => 'Manual'],
            // ['keterangan' => 'Otomatis'],

            // Untuk parameter_id 7 → validasi
            // ['keterangan' => 'Valid'],
            // ['keterangan' => 'Tidak Valid'],

            // Untuk parameter_id 8 → keputusan
            // ['keterangan' => 'Disetujui'],
            // ['keterangan' => 'Ditolak'],
            // ['keterangan' => 'Revisi'],

            // Untuk parameter_id 9 → koneksi
            // ['keterangan' => 'Terkoneksi'],
            // ['keterangan' => 'Tidak Terkoneksi'],
        ]);

        // Simpan id kategori dan satuan
        $kategori = KategoriParameter::pluck('id', 'nama');
        $satuan = Satuan::pluck('id', 'nama');
        $parameters = [
            [
                'nama' => 'Tebu Tergiling',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Kuintal'],
                'simbol' => 'tebu',
                'keterangan' => 'Kuintal Tebu Tergiling',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Totalizer Nira Mentah Pemurnian',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 't_nmp',
                'keterangan' => 'Totalizer Nira Mentah Pemurnian',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Totalizer Nira Mentah Gilingan',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 't_nmg',
                'keterangan' => 'Totalizer Nira Mentah Gilingan',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Totalizer Imbibisi',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 't_imb',
                'keterangan' => 'Totalizer Imbibisi',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Totalizer Decanter 1st Stage',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 't_d1',
                'keterangan' => 'Totalizer Decanter 1st Stage',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Totalizer Decanter 2nd Stage',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 't_d2',
                'keterangan' => 'Totalizer Decanter 2nd Stage',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],

            [
                'nama' => 'Flow Nira Mentah Pemurnian',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 'flow_nmp',
                'keterangan' => 'Flow Nira Mentah Pemurnian',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Flow Nira Mentah Gilingan',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 'flow_nmg',
                'keterangan' => 'Flow Nira Mentah Gilingan',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Flow Imbibisi',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 'flow_imb',
                'keterangan' => 'Flow Imbibisi',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Flow Decanter 1st Stage',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 'flow_d1',
                'keterangan' => 'Flow Decanter 1st Stage',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Flow Decanter 2nd Stage',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Meter Kubik'],
                'simbol' => 'flow_d2',
                'keterangan' => 'Flow Decanter 2nd Stage',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Nira Mentah Pemurnian % Tebu',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'nmp%tebu',
                'keterangan' => 'Nira Mentah Pemurnian % Tebu',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Nira Mentah Gilingan % Tebu',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'nmg%tebu',
                'keterangan' => 'Nira Mentah Gilingan % Tebu',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Imbibisi % Tebu',
                'kategori_parameter_id' => $kategori['Proses'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'imb%tebu',
                'keterangan' => 'Imbibisi % Tebu',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Brix',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'brix',
                'keterangan' => '%Brix',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Pol',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'pol',
                'keterangan' => '%Pol',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Pol Baca',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Derajat Pol'],
                'simbol' => 'polB',
                'keterangan' => 'Pol Baca',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'HK',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'hk',
                'keterangan' => '%HK',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Rendemen',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'r',
                'keterangan' => 'Rendemen',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'ICUMSA',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['ICUMSA'],
                'simbol' => 'IU',
                'keterangan' => 'Warna Larutan',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Moisture Content',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'mc',
                'keterangan' => 'Kadar Cairan',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Zat Kering',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'zk',
                'keterangan' => 'Zat Kering',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'CaO',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'caO',
                'keterangan' => 'Kadar CaO',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Keasaman',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['pH'],
                'simbol' => 'pH',
                'keterangan' => 'Keasaman',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Turbidity',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Nephelometric Turbidity Unit'],
                'simbol' => 'turb',
                'keterangan' => 'Kekeruhan',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'TDS',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['PPM'],
                'simbol' => 'tds',
                'keterangan' => 'Jumlah Padatan Terlarut',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Hardness',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['PPM'],
                'simbol' => 'sadah',
                'keterangan' => 'Kesadahan',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Fosfor Pentoksida',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['PPM'],
                'simbol' => 'p2O5',
                'keterangan' => 'Fosfor Pentoksida',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Sulfur Dioksida',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'so2',
                'keterangan' => 'Sulfur Dioksida',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Sugar Diameter',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Milimeter'],
                'simbol' => 'bjb',
                'keterangan' => 'Diameter Kristal',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Total Sugar As Invert',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'tsai',
                'keterangan' => 'Total Sugar As Invert',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Succrose',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'succrose',
                'keterangan' => 'Succrose',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Fructose',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'fructose',
                'keterangan' => 'Fructose',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Glucose',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'glucose',
                'keterangan' => 'Glucose',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Temperatur',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Celcius'],
                'simbol' => 'suhu',
                'keterangan' => 'Temperatur',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Preparation Index',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'pi',
                'keterangan' => 'Preparation Index',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Kadar Sabut',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'sabut',
                'keterangan' => 'Kadar Sabut',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Kadar Kapur',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'kapur',
                'keterangan' => 'Kadar Kapur',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Pol Ampas',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'polA',
                'keterangan' => 'Pol Ampas',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Fosfat',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'fosfat',
                'keterangan' => 'Kadar Fosfat',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Gula Reduksi',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'gured',
                'keterangan' => 'Gula Reduksi',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Saccharosa',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'saccharosa',
                'keterangan' => 'Saccharosa',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Optical Density',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'od',
                'keterangan' => 'Optical Density',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Dextran',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'dext',
                'keterangan' => 'Dextran',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Berat Kg',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Kilogram'],
                'simbol' => 'berat',
                'keterangan' => 'Berat dalam Kg',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Dispersitas',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'disp',
                'keterangan' => 'Dispersitas',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Silika',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'silika',
                'keterangan' => 'Silika',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Ampas',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'ampas',
                'keterangan' => '%Ampas',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Brixwegger',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Persen'],
                'simbol' => 'brixw',
                'keterangan' => 'Brixwegger',
                'metode_agregasi' => 'avg',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Nomor Pan',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Pan'],
                'simbol' => 'pan',
                'keterangan' => 'Nomor Pan',
                'metode_agregasi' => 'count',
                'jenis' => 'kuantitatif',
            ],
            [
                'nama' => 'Volume Masakan',
                'kategori_parameter_id' => $kategori['Analisa Lab'],
                'satuan_id' => $satuan['Hectoliter'],
                'simbol' => 'v',
                'keterangan' => 'Volume Masakan',
                'metode_agregasi' => 'sum',
                'jenis' => 'kuantitatif',
            ],
        ];
        foreach ($parameters as $parameter) {
            Parameter::create($parameter);
        }

        // Insert zona
        Zona::insert([
            ['kode' => 'GIL', 'nama' => 'Gilingan'],
            ['kode' => 'PMN', 'nama' => 'Pemurnian'],
            ['kode' => 'UAP', 'nama' => 'Penguapan'],
            ['kode' => 'MSK', 'nama' => 'Masakan'],
            ['kode' => 'DRK', 'nama' => 'DRK'],
            ['kode' => 'PTR', 'nama' => 'Puteran'],
            ['kode' => 'PCK', 'nama' => 'Packer'],
            ['kode' => 'LST', 'nama' => 'Listrik'],
            ['kode' => 'KTL', 'nama' => 'Ketel'],
            ['kode' => 'UPLC', 'nama' => 'UPLC'],
            ['kode' => 'TNGK', 'nama' => 'Tangki Tetes'],
            ['kode' => 'OTH', 'nama' => 'Lain-lain'],
        ]);

        $zona = Zona::pluck('id', 'kode');
        TitikPengamatan::insert([
            ['urutan' => 1, 'nama' => 'Material Balance', 'kode' => 'MB', 'zona_id' => $zona['OTH'], 'keterangan' => 'Material Balance'],
            ['urutan' => 2, 'nama' => 'Nira Gilingan 1', 'kode' => 'NPP', 'zona_id' => $zona['GIL'], 'keterangan' => 'Nira Gilingan 1'],
            ['urutan' => 3, 'nama' => 'Nira Gilingan 2', 'kode' => 'NG2', 'zona_id' => $zona['GIL'], 'keterangan' => 'Nira Gilingan 2'],
            ['urutan' => 4, 'nama' => 'Nira Gilingan 3', 'kode' => 'NG3', 'zona_id' => $zona['GIL'], 'keterangan' => 'Nira Gilingan 3'],
            ['urutan' => 5, 'nama' => 'Nira Gilingan 4', 'kode' => 'NG4', 'zona_id' => $zona['GIL'], 'keterangan' => 'Nira Gilingan 4'],
            ['urutan' => 6, 'nama' => 'Nira Gilingan 5', 'kode' => 'NG5', 'zona_id' => $zona['GIL'], 'keterangan' => 'Nira Gilingan 5'],
            ['urutan' => 7, 'nama' => 'Ampas Gilingan 1', 'kode' => 'AG1', 'zona_id' => $zona['GIL'], 'keterangan' => 'Ampas Gilingan 1'],
            ['urutan' => 8, 'nama' => 'Ampas Gilingan 2', 'kode' => 'AG2', 'zona_id' => $zona['GIL'], 'keterangan' => 'Ampas Gilingan 2'],
            ['urutan' => 9, 'nama' => 'Ampas Gilingan 3', 'kode' => 'AG3', 'zona_id' => $zona['GIL'], 'keterangan' => 'Ampas Gilingan 3'],
            ['urutan' => 10, 'nama' => 'Ampas Gilingan 4', 'kode' => 'AG4', 'zona_id' => $zona['GIL'], 'keterangan' => 'Ampas Gilingan 4'],
            ['urutan' => 11, 'nama' => 'Ampas Gilingan 5', 'kode' => 'AG5', 'zona_id' => $zona['GIL'], 'keterangan' => 'Ampas Gilingan 5'],
            // ['urutan' => 7, 'nama' => 'Cane Cutter', 'kode' => 'CC', 'zona_id' => $zona['GIL'], 'keterangan' => 'Mesin Pencacah Tebu'],
            ['urutan' => 12, 'nama' => 'Nira Mentah', 'kode' => 'NM', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Mentah'],
            ['urutan' => 13, 'nama' => 'Nira Reaction', 'kode' => 'NR', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira di Reaction Tank'],
            ['urutan' => 14, 'nama' => 'Nira Tapis', 'kode' => 'NT', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Tapis'],
            ['urutan' => 15, 'nama' => 'Nira Encer', 'kode' => 'NE', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Encer'],
            ['urutan' => 16, 'nama' => 'Nira Defekasi', 'kode' => 'ND', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Defekasi'],
            ['urutan' => 17, 'nama' => 'Nira Kotor', 'kode' => 'Nirkot', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Kotor'],
            ['urutan' => 18, 'nama' => 'Nira Pre Liming', 'kode' => 'NPL', 'zona_id' => $zona['PMN'], 'keterangan' => 'Nira Pre Liming'],
            ['urutan' => 19, 'nama' => 'RVF1', 'kode' => 'RVF1', 'zona_id' => $zona['PMN'], 'keterangan' => 'RVF1'],
            ['urutan' => 20, 'nama' => 'RVF2', 'kode' => 'RVF2', 'zona_id' => $zona['PMN'], 'keterangan' => 'RVF2'],
            ['urutan' => 21, 'nama' => 'RVF3', 'kode' => 'RVF3', 'zona_id' => $zona['PMN'], 'keterangan' => 'RVF3'],
            ['urutan' => 22, 'nama' => 'RVF4', 'kode' => 'RVF4', 'zona_id' => $zona['PMN'], 'keterangan' => 'RVF4'],
            ['urutan' => 23, 'nama' => 'Blotong Decanter 1', 'kode' => 'BDEC1', 'zona_id' => $zona['PMN'], 'keterangan' => 'Blotong Decanter 1'],
            ['urutan' => 24, 'nama' => 'Blotong Decanter 2', 'kode' => 'BDEC2', 'zona_id' => $zona['PMN'], 'keterangan' => 'Blotong Decanter 2'],
            ['urutan' => 25, 'nama' => 'Blotong Decanter 3', 'kode' => 'BDEC3', 'zona_id' => $zona['PMN'], 'keterangan' => 'Blotong Decanter 3'],
            ['urutan' => 26, 'nama' => 'Blotong Decanter 4', 'kode' => 'BDEC4', 'zona_id' => $zona['PMN'], 'keterangan' => 'Blotong Decanter 4'],
            ['urutan' => 27, 'nama' => 'Filtrat Decanter 1', 'kode' => 'FDEC1', 'zona_id' => $zona['PMN'], 'keterangan' => 'Filtrat Decanter 1'],
            ['urutan' => 28, 'nama' => 'Filtrat Decanter 2', 'kode' => 'FDEC2', 'zona_id' => $zona['PMN'], 'keterangan' => 'Filtrat Decanter 2'],
            ['urutan' => 29, 'nama' => 'Filtrat Decanter 3', 'kode' => 'FDEC3', 'zona_id' => $zona['PMN'], 'keterangan' => 'Filtrat Decanter 3'],
            ['urutan' => 30, 'nama' => 'Filtrat Decanter 4', 'kode' => 'FDEC4', 'zona_id' => $zona['PMN'], 'keterangan' => 'Filtrat Decanter 4'],
            ['urutan' => 31, 'nama' => 'Nira Kental', 'kode' => 'NK1', 'zona_id' => $zona['UAP'], 'keterangan' => 'Nira Kental'],
            ['urutan' => 32, 'nama' => 'Lamela In', 'kode' => 'LMI', 'zona_id' => $zona['UAP'], 'keterangan' => 'Lamela In'],
            ['urutan' => 33, 'nama' => 'Lamela Out', 'kode' => 'LMO', 'zona_id' => $zona['UAP'], 'keterangan' => 'Lamela Out'],
            ['urutan' => 34, 'nama' => 'Magma A Raw', 'kode' => 'MGAR', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma A Raw'],
            ['urutan' => 35, 'nama' => 'Magma Avinasi', 'kode' => 'MGAV', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma Avinasi'],
            ['urutan' => 36, 'nama' => 'Magma C', 'kode' => 'MGC', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma C (Einwuurf C)'],
            ['urutan' => 37, 'nama' => 'Magma D1', 'kode' => 'MGD1', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma D1'],
            ['urutan' => 38, 'nama' => 'Magma D2', 'kode' => 'MGD2', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma D2 (Einwuurf D)'],
            ['urutan' => 39, 'nama' => 'Magma RS', 'kode' => 'MGRS', 'zona_id' => $zona['MSK'], 'keterangan' => 'Magma RS'],
            ['urutan' => 40, 'nama' => 'Masakan A', 'kode' => 'MSKA', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan A'],
            ['urutan' => 41, 'nama' => 'Masakan A Raw', 'kode' => 'MSKAr', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan A Raw'],
            ['urutan' => 42, 'nama' => 'Masakan C', 'kode' => 'MSKC', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan C'],
            ['urutan' => 43, 'nama' => 'Masakan D1', 'kode' => 'MSKD1', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan D1'],
            ['urutan' => 44, 'nama' => 'Masakan D2', 'kode' => 'MSKD2', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan D2'],
            ['urutan' => 45, 'nama' => 'Masakan R1', 'kode' => 'MSKR1', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan R1'],
            ['urutan' => 46, 'nama' => 'Masakan R2', 'kode' => 'MSKR2', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan R2'],
            ['urutan' => 47, 'nama' => 'Masakan R3', 'kode' => 'MSKR3', 'zona_id' => $zona['MSK'], 'keterangan' => 'Masakan R3'],
            ['urutan' => 48, 'nama' => 'Masakan CVP A', 'kode' => 'CVPA', 'zona_id' => $zona['MSK'], 'keterangan' => 'CVP A'],
            ['urutan' => 49, 'nama' => 'Masakan CVP C', 'kode' => 'CVPC', 'zona_id' => $zona['MSK'], 'keterangan' => 'CVP C'],
            ['urutan' => 50, 'nama' => 'Masakan CVP D', 'kode' => 'CVPD', 'zona_id' => $zona['MSK'], 'keterangan' => 'CVP D'],
            ['urutan' => 51, 'nama' => 'Klare RS', 'kode' => 'KLRS', 'zona_id' => $zona['PTR'], 'keterangan' => 'Klare RS'],
            ['urutan' => 52, 'nama' => 'Klare SHS', 'kode' => 'KLSH', 'zona_id' => $zona['PTR'], 'keterangan' => 'Klare SHS'],
            ['urutan' => 53, 'nama' => 'Klare D', 'kode' => 'KLD', 'zona_id' => $zona['PTR'], 'keterangan' => 'Klare D'],
            ['urutan' => 54, 'nama' => 'Stroop A', 'kode' => 'SAB', 'zona_id' => $zona['PTR'], 'keterangan' => 'Stroop A'],
            ['urutan' => 55, 'nama' => 'Stroop C', 'kode' => 'SCB', 'zona_id' => $zona['PTR'], 'keterangan' => 'Stroop C'],
            ['urutan' => 56, 'nama' => 'R1 Mol', 'kode' => 'R1B', 'zona_id' => $zona['PTR'], 'keterangan' => 'R1 Mol'],
            ['urutan' => 57, 'nama' => 'R2 Mol', 'kode' => 'R2B', 'zona_id' => $zona['PTR'], 'keterangan' => 'R2 Mol'],
            ['urutan' => 58, 'nama' => 'Remelter A', 'kode' => 'RAB', 'zona_id' => $zona['PTR'], 'keterangan' => 'Remelter A'],
            ['urutan' => 59, 'nama' => 'Remelter C/D', 'kode' => 'RCDB', 'zona_id' => $zona['PTR'], 'keterangan' => 'Remelter C/D'],
            ['urutan' => 60, 'nama' => 'Tetes Puteran', 'kode' => 'TTSP', 'zona_id' => $zona['PTR'], 'keterangan' => 'Tetes Puteran'],
            ['urutan' => 61, 'nama' => 'Material Siwaran', 'kode' => 'MTS', 'zona_id' => $zona['PTR'], 'keterangan' => 'Material Siwaran'],
            ['urutan' => 62, 'nama' => 'RS Kedatangan', 'kode' => 'RSK', 'zona_id' => $zona['PTR'], 'keterangan' => 'RS Kedatangan'],
            ['urutan' => 63, 'nama' => 'Gula RS In', 'kode' => 'RSI', 'zona_id' => $zona['PTR'], 'keterangan' => 'RS In'],
            ['urutan' => 64, 'nama' => 'Gula Kristal Putih', 'kode' => 'GKP', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula Kristal Putih'],
            ['urutan' => 65, 'nama' => 'Gula Premium', 'kode' => 'GP', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula Premium'],
            ['urutan' => 66, 'nama' => 'Gula R2', 'kode' => 'GR2', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula R2'],
            ['urutan' => 67, 'nama' => 'Gula A Raw', 'kode' => 'GAr', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula A Raw'],
            ['urutan' => 68, 'nama' => 'Gula C', 'kode' => 'GC', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula C'],
            ['urutan' => 69, 'nama' => 'Gula D1', 'kode' => 'GD1', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula D1'],
            ['urutan' => 70, 'nama' => 'Gula D2', 'kode' => 'GD2', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula D2'],
            ['urutan' => 71, 'nama' => 'Gula RS Produk', 'kode' => 'GRS', 'zona_id' => $zona['PTR'], 'keterangan' => 'Gula RS Produk'],
            ['urutan' => 72, 'nama' => 'Tetes Tangki 1', 'kode' => 'TT1', 'zona_id' => $zona['TNGK'], 'keterangan' => 'Tetes Tangki 1'],
            ['urutan' => 73, 'nama' => 'Tetes Tangki 2', 'kode' => 'TT2', 'zona_id' => $zona['TNGK'], 'keterangan' => 'Tetes Tangki 2'],
            ['urutan' => 74, 'nama' => 'Tetes Tangki 3', 'kode' => 'TT3', 'zona_id' => $zona['TNGK'], 'keterangan' => 'Tetes Tangki 3'],
            ['urutan' => 75, 'nama' => 'Tetes Kumpulan', 'kode' => 'TK', 'zona_id' => $zona['TNGK'], 'keterangan' => 'Tetes Kumpulan'],
            ['urutan' => 76, 'nama' => 'Jiangxian Jianglian', 'kode' => 'JJ', 'zona_id' => $zona['KTL'], 'keterangan' => 'JJ'],
            ['urutan' => 77, 'nama' => 'Yoshimine 1', 'kode' => 'Y1', 'zona_id' => $zona['KTL'], 'keterangan' => 'Yoshimine 1'],
            ['urutan' => 78, 'nama' => 'Yoshimine 2', 'kode' => 'Y2', 'zona_id' => $zona['KTL'], 'keterangan' => 'Yoshimine 2'],
            ['urutan' => 79, 'nama' => 'WTP', 'kode' => 'WTP', 'zona_id' => $zona['KTL'], 'keterangan' => 'WTP'],
            ['urutan' => 80, 'nama' => 'HW', 'kode' => 'HW', 'zona_id' => $zona['KTL'], 'keterangan' => 'HW'],
            ['urutan' => 81, 'nama' => 'Daerator JJ', 'kode' => 'DJJ', 'zona_id' => $zona['KTL'], 'keterangan' => 'DJJ'],
            ['urutan' => 82, 'nama' => 'Daerator Yoshimine 1', 'kode' => 'DY1', 'zona_id' => $zona['KTL'], 'keterangan' => 'D Yoshimine 1'],
            ['urutan' => 83, 'nama' => 'Daerator Yoshimine 2', 'kode' => 'DY2', 'zona_id' => $zona['KTL'], 'keterangan' => 'D Yoshimine 2'],
            ['urutan' => 84, 'nama' => 'Remelter', 'kode' => 'RML', 'zona_id' => $zona['DRK'], 'keterangan' => 'Remelter'],
            ['urutan' => 85, 'nama' => 'Carbonated Liquor', 'kode' => 'CRB', 'zona_id' => $zona['DRK'], 'keterangan' => 'Carbonated Liquor'],
            ['urutan' => 86, 'nama' => 'Reaction Tank', 'kode' => 'RCT', 'zona_id' => $zona['DRK'], 'keterangan' => 'Reaction Tank'],
            ['urutan' => 87, 'nama' => 'Clear Liquor', 'kode' => 'CLR', 'zona_id' => $zona['DRK'], 'keterangan' => 'Clear Liquor'],
            ['urutan' => 88, 'nama' => 'Filter Cake Head', 'kode' => 'FCH', 'zona_id' => $zona['DRK'], 'keterangan' => 'Filter Cake Head'],
            ['urutan' => 89, 'nama' => 'Filter Cake Mid', 'kode' => 'FCM', 'zona_id' => $zona['DRK'], 'keterangan' => 'Filter Cake Mid'],
            ['urutan' => 90, 'nama' => 'Filter Cake End', 'kode' => 'FCE', 'zona_id' => $zona['DRK'], 'keterangan' => 'Filter Cake End'],
            ['urutan' => 91, 'nama' => 'Sweet Water', 'kode' => 'SWW', 'zona_id' => $zona['DRK'], 'keterangan' => 'Sweet Water'],
        ]);

        // Mapping titik dan parameter ke relasi
        $titik = TitikPengamatan::pluck('id', 'nama');
        $param = Parameter::pluck('id', 'nama');

        $relasi = [
            ['Material Balance', 'Tebu Tergiling'],
            ['Material Balance', 'Totalizer Nira Mentah Pemurnian'],
            ['Material Balance', 'Totalizer Nira Mentah Gilingan'],
            ['Material Balance', 'Totalizer Imbibisi'],
            ['Material Balance', 'Totalizer Decanter 1st Stage'],
            ['Material Balance', 'Totalizer Decanter 2nd Stage'],
            ['Material Balance', 'Flow Nira Mentah Pemurnian'],
            ['Material Balance', 'Flow Nira Mentah Gilingan'],
            ['Material Balance', 'Flow Imbibisi'],
            ['Material Balance', 'Flow Decanter 1st Stage'],
            ['Material Balance', 'Flow Decanter 2nd Stage'],
            ['Material Balance', 'Nira Mentah Pemurnian % Tebu'],
            ['Material Balance', 'Nira Mentah Gilingan % Tebu'],
            ['Material Balance', 'Imbibisi % Tebu'],
            ['Nira Gilingan 1', 'Brix'],
            ['Nira Gilingan 1', 'Pol'],
            ['Nira Gilingan 1', 'HK'],
            ['Nira Gilingan 1', 'Keasaman'],
            ['Nira Gilingan 1', 'Rendemen'],
            ['Nira Gilingan 1', 'ICUMSA'],
            ['Nira Gilingan 2', 'Brix'],
            ['Nira Gilingan 2', 'Pol'],
            ['Nira Gilingan 2', 'HK'],
            ['Nira Gilingan 2', 'Keasaman'],
            ['Nira Gilingan 3', 'Brix'],
            ['Nira Gilingan 3', 'Pol'],
            ['Nira Gilingan 3', 'HK'],
            ['Nira Gilingan 3', 'Keasaman'],
            ['Nira Gilingan 4', 'Brix'],
            ['Nira Gilingan 4', 'Pol'],
            ['Nira Gilingan 4', 'HK'],
            ['Nira Gilingan 4', 'Keasaman'],
            ['Nira Gilingan 5', 'Brix'],
            ['Nira Gilingan 5', 'Pol'],
            ['Nira Gilingan 5', 'HK'],
            ['Nira Gilingan 5', 'Keasaman'],
            ['Ampas Gilingan 1', 'Pol Ampas'],
            ['Ampas Gilingan 1', 'Zat Kering'],
            ['Ampas Gilingan 2', 'Pol Ampas'],
            ['Ampas Gilingan 2', 'Zat Kering'],
            ['Ampas Gilingan 3', 'Pol Ampas'],
            ['Ampas Gilingan 3', 'Zat Kering'],
            ['Ampas Gilingan 4', 'Pol Ampas'],
            ['Ampas Gilingan 4', 'Zat Kering'],
            ['Ampas Gilingan 5', 'Pol Ampas'],
            ['Ampas Gilingan 5', 'Zat Kering'],
            // ['Cane Cutter', 'Preparation Index'],
            // ['Cane Cutter', 'Kadar Sabut'],
            ['Nira Mentah', 'Brix'],
            ['Nira Mentah', 'Pol'],
            ['Nira Mentah', 'HK'],
            ['Nira Mentah', 'ICUMSA'],
            ['Nira Mentah', 'CaO'],
            ['Nira Mentah', 'Keasaman'],
            ['Nira Mentah', 'Turbidity'],
            ['Nira Mentah', 'Fosfat'],
            ['Nira Mentah', 'Gula Reduksi'],
            ['Nira Mentah', 'Dextran'],
            ['Nira Mentah', 'Ampas'],
            ['Nira Reaction', 'Brix'],
            ['Nira Reaction', 'Pol'],
            ['Nira Reaction', 'HK'],
            ['Nira Reaction', 'ICUMSA'],
            ['Nira Reaction', 'CaO'],
            ['Nira Reaction', 'Keasaman'],
            ['Nira Reaction', 'Turbidity'],
            ['Nira Tapis', 'Brix'],
            ['Nira Tapis', 'Pol'],
            ['Nira Tapis', 'HK'],
            ['Nira Tapis', 'ICUMSA'],
            ['Nira Tapis', 'CaO'],
            ['Nira Tapis', 'Keasaman'],
            ['Nira Tapis', 'Turbidity'],
            ['Nira Encer', 'Brix'],
            ['Nira Encer', 'Pol'],
            ['Nira Encer', 'HK'],
            ['Nira Encer', 'ICUMSA'],
            ['Nira Encer', 'CaO'],
            ['Nira Encer', 'Keasaman'],
            ['Nira Encer', 'Turbidity'],
            ['RVF1', 'Pol Baca'],
            ['RVF1', 'Moisture Content'],
            ['RVF2', 'Pol Baca'],
            ['RVF2', 'Moisture Content'],
            ['RVF3', 'Pol Baca'],
            ['RVF3', 'Moisture Content'],
            ['RVF4', 'Pol Baca'],
            ['RVF4', 'Moisture Content'],
            ['Nira Defekasi', 'Brix'],
            ['Nira Defekasi', 'Pol'],
            ['Nira Defekasi', 'HK'],
            ['Nira Defekasi', 'ICUMSA'],
            ['Nira Defekasi', 'CaO'],
            ['Nira Defekasi', 'Keasaman'],
            ['Nira Defekasi', 'Turbidity'],
            ['Nira Kotor', 'Brix'],
            ['Nira Kotor', 'Pol'],
            ['Nira Kotor', 'HK'],
            ['Nira Kotor', 'Zat Kering'],
            ['Blotong Decanter 1', 'Pol Baca'],
            ['Blotong Decanter 1', 'Moisture Content'],
            ['Blotong Decanter 2', 'Pol Baca'],
            ['Blotong Decanter 2', 'Moisture Content'],
            ['Blotong Decanter 3', 'Pol Baca'],
            ['Blotong Decanter 3', 'Moisture Content'],
            ['Blotong Decanter 4', 'Pol Baca'],
            ['Blotong Decanter 4', 'Moisture Content'],
            ['Filtrat Decanter 1', 'Brix'],
            ['Filtrat Decanter 1', 'Pol'],
            ['Filtrat Decanter 1', 'HK'],
            ['Filtrat Decanter 1', 'Turbidity'],
            ['Filtrat Decanter 2', 'Brix'],
            ['Filtrat Decanter 2', 'Pol'],
            ['Filtrat Decanter 2', 'HK'],
            ['Filtrat Decanter 2', 'Turbidity'],
            ['Filtrat Decanter 3', 'Brix'],
            ['Filtrat Decanter 3', 'Pol'],
            ['Filtrat Decanter 3', 'HK'],
            ['Filtrat Decanter 3', 'Turbidity'],
            ['Filtrat Decanter 4', 'Brix'],
            ['Filtrat Decanter 4', 'Pol'],
            ['Filtrat Decanter 4', 'HK'],
            ['Filtrat Decanter 4', 'Turbidity'],
            ['Nira Pre Liming', 'Brix'],
            ['Nira Pre Liming', 'Pol'],
            ['Nira Pre Liming', 'HK'],
            ['Nira Pre Liming', 'ICUMSA'],
            ['Nira Pre Liming', 'Keasaman'],
            ['Nira Pre Liming', 'Turbidity'],
            ['Nira Pre Liming', 'Fosfat'],
            ['Nira Kental', 'Brix'],
            ['Nira Kental', 'Pol'],
            ['Nira Kental', 'HK'],
            ['Nira Kental', 'ICUMSA'],
            ['Nira Kental', 'CaO'],
            ['Nira Kental', 'Keasaman'],
            ['Nira Kental', 'Turbidity'],
            ['Lamela In', 'Brix'],
            ['Lamela In', 'Pol'],
            ['Lamela In', 'HK'],
            ['Lamela In', 'ICUMSA'],
            ['Lamela In', 'CaO'],
            ['Lamela In', 'Keasaman'],
            ['Lamela In', 'Turbidity'],
            ['Lamela Out', 'Brix'],
            ['Lamela Out', 'Pol'],
            ['Lamela Out', 'HK'],
            ['Lamela Out', 'ICUMSA'],
            ['Lamela Out', 'CaO'],
            ['Lamela Out', 'Keasaman'],
            ['Lamela Out', 'Turbidity'],
            ['Magma A Raw', 'Brix'],
            ['Magma A Raw', 'Pol'],
            ['Magma A Raw', 'HK'],
            ['Magma A Raw', 'ICUMSA'],
            ['Magma Avinasi', 'Brix'],
            ['Magma Avinasi', 'Pol'],
            ['Magma Avinasi', 'HK'],
            ['Magma Avinasi', 'ICUMSA'],
            ['Magma C', 'Brix'],
            ['Magma C', 'Pol'],
            ['Magma C', 'HK'],
            ['Magma C', 'ICUMSA'],
            ['Magma D1', 'Brix'],
            ['Magma D1', 'Pol'],
            ['Magma D1', 'HK'],
            ['Magma D1', 'ICUMSA'],
            ['Magma D2', 'Brix'],
            ['Magma D2', 'Pol'],
            ['Magma D2', 'HK'],
            ['Magma D2', 'ICUMSA'],
            ['Magma RS', 'Brix'],
            ['Magma RS', 'Pol'],
            ['Magma RS', 'HK'],
            ['Magma RS', 'ICUMSA'],
            ['Masakan A Raw', 'Brix'],
            ['Masakan A Raw', 'Pol'],
            ['Masakan A Raw', 'HK'],
            ['Masakan A Raw', 'ICUMSA'],
            ['Masakan A Raw', 'Nomor Pan'],
            ['Masakan A Raw', 'Volume Masakan'],
            ['Masakan A', 'Brix'],
            ['Masakan A', 'Pol'],
            ['Masakan A', 'HK'],
            ['Masakan A', 'ICUMSA'],
            ['Masakan A', 'Nomor Pan'],
            ['Masakan A', 'Volume Masakan'],
            ['Masakan C', 'Brix'],
            ['Masakan C', 'Pol'],
            ['Masakan C', 'HK'],
            ['Masakan C', 'ICUMSA'],
            ['Masakan C', 'Nomor Pan'],
            ['Masakan C', 'Volume Masakan'],
            ['Masakan D1', 'Brix'],
            ['Masakan D1', 'Pol'],
            ['Masakan D1', 'HK'],
            ['Masakan D1', 'ICUMSA'],
            ['Masakan D1', 'Nomor Pan'],
            ['Masakan D1', 'Volume Masakan'],
            ['Masakan D2', 'Brix'],
            ['Masakan D2', 'Pol'],
            ['Masakan D2', 'HK'],
            ['Masakan D2', 'ICUMSA'],
            ['Masakan D2', 'Nomor Pan'],
            ['Masakan D2', 'Volume Masakan'],
            ['Masakan R1', 'Brix'],
            ['Masakan R1', 'Pol'],
            ['Masakan R1', 'HK'],
            ['Masakan R1', 'ICUMSA'],
            ['Masakan R1', 'Nomor Pan'],
            ['Masakan R1', 'Volume Masakan'],
            ['Masakan R2', 'Brix'],
            ['Masakan R2', 'Pol'],
            ['Masakan R2', 'HK'],
            ['Masakan R2', 'ICUMSA'],
            ['Masakan R2', 'Nomor Pan'],
            ['Masakan R2', 'Volume Masakan'],
            ['Masakan R3', 'Brix'],
            ['Masakan R3', 'Pol'],
            ['Masakan R3', 'HK'],
            ['Masakan R3', 'ICUMSA'],
            ['Masakan R3', 'Nomor Pan'],
            ['Masakan R3', 'Volume Masakan'],
            ['Masakan CVP A', 'Brix'],
            ['Masakan CVP A', 'Pol'],
            ['Masakan CVP A', 'HK'],
            ['Masakan CVP A', 'ICUMSA'],
            ['Masakan CVP C', 'Brix'],
            ['Masakan CVP C', 'Pol'],
            ['Masakan CVP C', 'HK'],
            ['Masakan CVP C', 'ICUMSA'],
            ['Masakan CVP D', 'Brix'],
            ['Masakan CVP D', 'Pol'],
            ['Masakan CVP D', 'HK'],
            ['Masakan CVP D', 'ICUMSA'],
            ['Klare RS', 'Brix'],
            ['Klare RS', 'Pol'],
            ['Klare RS', 'HK'],
            ['Klare RS', 'ICUMSA'],
            ['Klare SHS', 'Brix'],
            ['Klare SHS', 'Pol'],
            ['Klare SHS', 'HK'],
            ['Klare SHS', 'ICUMSA'],
            ['Klare D', 'Brix'],
            ['Klare D', 'Pol'],
            ['Klare D', 'HK'],
            ['Klare D', 'ICUMSA'],
            ['Stroop A', 'Brix'],
            ['Stroop A', 'Pol'],
            ['Stroop A', 'HK'],
            ['Stroop A', 'ICUMSA'],
            ['Stroop C', 'Brix'],
            ['Stroop C', 'Pol'],
            ['Stroop C', 'HK'],
            ['Stroop C', 'ICUMSA'],
            ['R1 Mol', 'Brix'],
            ['R1 Mol', 'Pol'],
            ['R1 Mol', 'HK'],
            ['R1 Mol', 'ICUMSA'],
            ['R2 Mol', 'Brix'],
            ['R2 Mol', 'Pol'],
            ['R2 Mol', 'HK'],
            ['R2 Mol', 'ICUMSA'],
            ['Remelter A', 'Brix'],
            ['Remelter A', 'Pol'],
            ['Remelter A', 'HK'],
            ['Remelter A', 'ICUMSA'],
            ['Remelter C/D', 'Brix'],
            ['Remelter C/D', 'Pol'],
            ['Remelter C/D', 'HK'],
            ['Remelter C/D', 'ICUMSA'],
            ['Tetes Puteran', 'Brix'],
            ['Tetes Puteran', 'Pol'],
            ['Tetes Puteran', 'HK'],
            ['Tetes Puteran', 'ICUMSA'],
            ['Material Siwaran', 'Brix'],
            ['Material Siwaran', 'Pol'],
            ['Material Siwaran', 'HK'],
            ['Material Siwaran', 'ICUMSA'],
            ['RS Kedatangan', 'Brix'],
            ['RS Kedatangan', 'Pol'],
            ['RS Kedatangan', 'HK'],
            ['RS Kedatangan', 'ICUMSA'],
            ['RS Kedatangan', 'Moisture Content'],
            ['Gula RS In', 'Brix'],
            ['Gula RS In', 'Pol'],
            ['Gula RS In', 'HK'],
            ['Gula RS In', 'ICUMSA'],
            ['Gula RS In', 'Moisture Content'],
            ['Gula Kristal Putih', 'Brix'],
            ['Gula Kristal Putih', 'Pol'],
            ['Gula Kristal Putih', 'HK'],
            ['Gula Kristal Putih', 'ICUMSA'],
            ['Gula Kristal Putih', 'Moisture Content'],
            ['Gula Premium', 'Brix'],
            ['Gula Premium', 'Pol'],
            ['Gula Premium', 'HK'],
            ['Gula Premium', 'ICUMSA'],
            ['Gula Premium', 'Moisture Content'],
            ['Gula R2', 'Brix'],
            ['Gula R2', 'Pol'],
            ['Gula R2', 'HK'],
            ['Gula R2', 'ICUMSA'],
            ['Gula R2', 'Moisture Content'],
            ['Gula A Raw', 'Brix'],
            ['Gula A Raw', 'Pol'],
            ['Gula A Raw', 'HK'],
            ['Gula A Raw', 'ICUMSA'],
            ['Gula A Raw', 'Moisture Content'],
            ['Gula C', 'Brix'],
            ['Gula C', 'Pol'],
            ['Gula C', 'HK'],
            ['Gula C', 'ICUMSA'],
            ['Gula C', 'Moisture Content'],
            ['Gula D1', 'Brix'],
            ['Gula D1', 'Pol'],
            ['Gula D1', 'HK'],
            ['Gula D1', 'ICUMSA'],
            ['Gula D1', 'Moisture Content'],
            ['Gula D2', 'Brix'],
            ['Gula D2', 'Pol'],
            ['Gula D2', 'HK'],
            ['Gula D2', 'ICUMSA'],
            ['Gula D2', 'Moisture Content'],
            ['Gula RS Produk', 'Brix'],
            ['Gula RS Produk', 'Pol'],
            ['Gula RS Produk', 'HK'],
            ['Gula RS Produk', 'ICUMSA'],
            ['Gula RS Produk', 'Moisture Content'],
            ['Tetes Tangki 1', 'Brixwegger'],
            ['Tetes Tangki 1', 'Total Sugar As Invert'],
            ['Tetes Tangki 2', 'Brixwegger'],
            ['Tetes Tangki 2', 'Total Sugar As Invert'],
            ['Tetes Tangki 3', 'Brixwegger'],
            ['Tetes Tangki 3', 'Total Sugar As Invert'],
            ['Tetes Kumpulan', 'Brixwegger'],
            ['Tetes Kumpulan', 'Total Sugar As Invert'],
            ['Jiangxian Jianglian', 'Keasaman'],
            ['Jiangxian Jianglian', 'TDS'],
            ['Jiangxian Jianglian', 'Hardness'],
            ['Jiangxian Jianglian', 'Fosfor Pentoksida'],
            ['Jiangxian Jianglian', 'Silika'],
            ['Yoshimine 1', 'Keasaman'],
            ['Yoshimine 1', 'TDS'],
            ['Yoshimine 1', 'Hardness'],
            ['Yoshimine 1', 'Fosfor Pentoksida'],
            ['Yoshimine 1', 'Silika'],
            ['Yoshimine 2', 'Keasaman'],
            ['Yoshimine 2', 'TDS'],
            ['Yoshimine 2', 'Hardness'],
            ['Yoshimine 2', 'Fosfor Pentoksida'],
            ['Yoshimine 2', 'Silika'],
            ['WTP', 'Keasaman'],
            ['WTP', 'TDS'],
            ['WTP', 'Hardness'],
            ['WTP', 'Silika'],
            ['HW', 'Keasaman'],
            ['HW', 'TDS'],
            ['Daerator JJ', 'Keasaman'],
            ['Daerator JJ', 'TDS'],
            ['Daerator Yoshimine 1', 'Keasaman'],
            ['Daerator Yoshimine 1', 'TDS'],
            ['Daerator Yoshimine 2', 'Keasaman'],
            ['Daerator Yoshimine 2', 'TDS'],
            ['Remelter', 'Brix'],
            ['Remelter', 'Pol'],
            ['Remelter', 'HK'],
            ['Remelter', 'ICUMSA'],
            ['Remelter', 'CaO'],
            ['Remelter', 'Keasaman'],
            ['Remelter', 'Turbidity'],
            ['Reaction Tank', 'Brix'],
            ['Reaction Tank', 'Pol'],
            ['Reaction Tank', 'HK'],
            ['Reaction Tank', 'ICUMSA'],
            ['Reaction Tank', 'CaO'],
            ['Reaction Tank', 'Keasaman'],
            ['Reaction Tank', 'Turbidity'],
            ['Carbonated Liquor', 'Brix'],
            ['Carbonated Liquor', 'Pol'],
            ['Carbonated Liquor', 'HK'],
            ['Carbonated Liquor', 'ICUMSA'],
            ['Carbonated Liquor', 'CaO'],
            ['Carbonated Liquor', 'Keasaman'],
            ['Carbonated Liquor', 'Turbidity'],
            ['Clear Liquor', 'Brix'],
            ['Clear Liquor', 'Pol'],
            ['Clear Liquor', 'HK'],
            ['Clear Liquor', 'ICUMSA'],
            ['Clear Liquor', 'CaO'],
            ['Clear Liquor', 'Keasaman'],
            ['Clear Liquor', 'Turbidity'],
            ['Sweet Water', 'Brix'],
            ['Sweet Water', 'Pol'],
            ['Sweet Water', 'HK'],
            ['Sweet Water', 'ICUMSA'],
            ['Sweet Water', 'CaO'],
            ['Sweet Water', 'Keasaman'],
            ['Sweet Water', 'Turbidity'],
            ['Filter Cake Head', 'Pol Baca'],
            ['Filter Cake Head', 'Moisture Content'],
            ['Filter Cake Mid', 'Pol Baca'],
            ['Filter Cake Mid', 'Moisture Content'],
            ['Filter Cake End', 'Pol Baca'],
            ['Filter Cake End', 'Moisture Content'],
        ];

        $insert = [];

        foreach ($relasi as [$titikNama, $paramNama]) {
            if (isset($titik[$titikNama], $param[$paramNama])) {
                $insert[] = [
                    'titik_pengamatan_id' => $titik[$titikNama],
                    'parameter_id' => $param[$paramNama],
                ];
            }
        }

        // Insert ke tabel pivot parameter_titik_pengamatan
        ParameterTitikPengamatan::insert($insert);

        // Seeder KategoriParameter dan Zona sudah dijalankan sebelum ini
        // Tambahkan kolom roles yang sesuai dari KategoriParameter
        foreach (KategoriParameter::all() as $kategori) {
            $columnName = 'akses_monitoring_kategori' . Str::slug($kategori->id, '_');

            if (!Schema::hasColumn('roles', $columnName)) {
                Schema::table('roles', function ($table) use ($columnName) {
                    $table->boolean($columnName)->default(false)->after('updated_at');
                });
            }
        }

        // Tambahkan kolom roles yang sesuai dari Zona
        foreach (Zona::all() as $zona) {
            $columnName = 'akses_monitoring_zona' . Str::slug($zona->id, '_');

            if (!Schema::hasColumn('roles', $columnName)) {
                Schema::table('roles', function ($table) use ($columnName) {
                    $table->boolean($columnName)->default(false)->after('updated_at');
                });
            }
        }

        // Buka semua akses
        $data = [];
        foreach (Role::semua_akses2() as $akses) {
            $data[$akses] = 1;
        }
        Role::query()->update($data);
    }
}
